name: "AutoSSH Tunnel"
version: "1.0.4"
slug: "autossh_tunnel"
description: "Reverse SSH tunnel to service.tilda.com.tr for HA 8123"

arch:
  - aarch64
  - armv7
  - armhf

startup: services
boot: auto
host_network: true

options:
  user: "youruseronserverhere"
  host: "like.yourhost.com"
  remote_bind: "like.yourhost.com:8123"
  local_target: "ha.local:8123"

schema:
  user: 
    type: str
    description: "your username on the server like username@bigcompany.com"

  host:
    type: str
    description: "your server to connect to like bigcompany.com"

  remote_bind:
    type: str
    description: "like bigcompany.com:8123 8123 on this server will be forwarded back to local_target"

  local_target:
    type: str
    description: "most likely ha.local:8123 or 192.168.0.52:8123, keep in mind that because this will run in a docker container, 127.0.0.1 or localhost most likely won't be what you're looking for."

map:
  - config:rw

